function Answer = FcnDefine

FD = dialog('Name', 'Function Define', ...
    'Unit'          , 'pixel', ...
    'Position'      , [0, 0, 375, 220], ...
    'Userdata'      , 'Cancel', ...
    'KeyPressFcn'   , @doFigureKeyPress, ...
    'Visible'       , 'off' ...
    );
set(FD,'Position',getnicedialoglocation(get(FD, 'Position'),get(FD,'Units')));

StatementHaandle = uicontrol(FD, ...
    'Style'                 , 'text', ...
    'String'                , {'Use function to define the unit num of each layer.'; ...
                                'Please use MATLAB programming language.'}, ...
    'Unit'                  , 'pixel', ...
    'Position'              , [25, 180, 250, 30], ...
    'HorizontalAlignment'   , 'left', ...
    'Tag'                   , 'Statement' ...
    );  %#ok

EquationLeftHandle = uicontrol(FD, ...
    'Style'                 , 'text', ...
    'String'                , 'UnitNum(ii) = ', ...
    'Unit'                  , 'pixel', ...
    'Position'              , [25, 140, 67, 15], ...
    'HorizontalAlignment'   , 'left', ...
    'Tag'                   , 'EquationLeft' ...
    );  %#ok

EquationRight = uicontrol(FD, ...
    'Style'                 , 'edit', ...
    'String'                , '', ...
    'Unit'                  , 'pixel', ...
    'Position'              , [92, 45, 250, 110], ...
    'HorizontalAlignment'   , 'left', ...
    'Tag'                   , 'EquationRight', ...
    'Max'                   , 10, ...
    'Min'                   , 0, ...
    'BackgroundColor'       , 'white' ...
    ); 

OKBtn = uicontrol(FD, ...
    'Style'         , 'pushbutton', ...
    'String'        , getString(message('MATLAB:uistring:popupdialogs:OK')), ...
    'Unit'          , 'pixel', ...
    'Position'      , [170, 12, 60, 20], ...
    'Callback'      , @doCallback, ...
    'KeyPressFcn'   , @doControlKeyPress, ...
    'Tag'           , 'OK', ...
    'Userdata'      , 'OK' ...
    ); %#ok

CancelBtn = uicontrol(FD, ...
    'Style'         , 'pushbutton', ...
    'String'        , getString(message('MATLAB:uistring:popupdialogs:Cancel')), ...
    'Unit'          , 'pixel', ...
    'Position'      , [270, 12, 60, 20], ...
    'Callback'      , @doCallback, ...
    'KeyPressFcn'   , @doControlKeyPress, ...
    'Tag'           , 'Cancel', ...
    'Userdata'      , 'Cancel' ...
    ); %#ok')

% make sure we are on screen
movegui(FD);

% if there is a figure out there and it's modal, we need to be modal too
if ~isempty(gcbf) && strcmp(get(gcbf,'WindowStyle'),'modal')
  set(FD,'WindowStyle','modal');
end

set(FD,'Visible','on');
drawnow;

if ishghandle(FD)
    % Go into uiwait if the figure handle is still valid.
    % This is mostly the case during regular use.
    uiwait(FD);
end

% Check handle validity again since we may be out of uiwait because the
% figure was deleted.
if ishghandle(FD)
    Answer = {};
    if strcmp(get(FD, 'UserData'), 'OK'),
        Answer = get(EquationRight,{'String'});
    end
    delete(FD);
else
    Answer = {};
end

function doFigureKeyPress(obj, evd) %#ok
switch(evd.Key)
    case {'return','space'}
        set(gcbf,'UserData','OK');
        uiresume(gcbf);
    case {'escape'}
        delete(gcbf);
end

function doControlKeyPress(obj, evd) 
switch(evd.Key)
  case {'return'}
    if ~strcmp(get(obj,'UserData'),'Cancel')
      set(gcbf,'UserData','OK');
      uiresume(gcbf);
    else
      delete(gcbf);
    end
  case {'escape'}
    delete(gcbf);
end

function doCallback(obj, evd) %#ok
if ~strcmp(get(obj,'UserData'),'Cancel')
  set(gcbf,'UserData','OK');
  uiresume(gcbf);
else
  delete(gcbf);
end